### ISSUE TITLE
[fe] 카드 이동

### ISSUE THREAD

**Issue by youzysu** [todo-team-01/todo-max#40]
## TO-BE

요구사항
- Drag and Drop를 브라우저 API없이 직접 구현한다.
- onMousemove, onMousedown 등의 Mouse 이벤트를 활용한다.

### 이동 경로의 절반이 넘으면 카드의 예정 목적지로 카드의 잔상이 이동한다.
- GhostInfo에 draggingCard로 GhostCard를 만든다.

### Drag를 중단하면 카드는 현재 잔상이 있는 위치로 이동한다.

  Close #74

**Comment by youzysu** [comment]
## Main
- TodoProvider

### State
1. columnList
2. targetCardInfo
3. targetPositionInfo: {targetColumnId, targetIndex}
4. isDragging

- columnList는 targetPositionInfo가 변경될 때 함께 업데이트 된다.
- targetCardId에 해당하는 Card는 opacity: 30%, 일반 Card는 opacity: 100%로 렌더링된다.

### onMousedown
- setTargetCardInfo(targetCardInfo)
- 현재 위치로 setTargetPositionInfo
- 해당 정보로 Dragging Card를 만든다.

### onMousemove
- Column에서 mousemove 이벤트로 offset 위치에 따라 cardIndex
- dragOffsetX, dragOffsetY 위치에 따라 Dragging Card가 움직인다.
- dragOffsetX, dragOffsetY 위치에 따라 setTargetPositionInfo가 지속적으로 변경된다.

### onMouseup
- 현재 targetPositionInfo와 columnList를 기반으로 목적지 TopCardId, BottomCardId를 body에 담아`PATCH /cards/{id}` 요청을 보낸다.
- `onCardChanged` 전체 columnList 업데이트한다.

**Comment by youzysu** [comment]
<현재 로직>
Main
- mousedown되면 선택된 card의 Data를 상태로 가진다. cloneCardData
- 마우스를 따라 이동하는 CloneCard가 Main에서 렌더링된다.

**Comment by youzysu** [comment]
# Bug
- [ ] 카드 수정 버튼이나 취소 버튼 클릭 시 카드 이동되는 문제
- [ ] 새로운 칼럼으로 이동되지 않는 문제

**Comment by altmit** [comment]
# Bug
- [ ] card에 버튼을 클릭했는데 드래그가 되는 현상
- [ ] 카드 드래그 후 사라지는 현상

**Comment by altmit** [comment]
# 성능 문제 개선
- 마우스에 따라 움직이는 컴포넌트가 너무 느렸던 문제
- 마우스가 빠르게 움직이면 컴포넌트를 놓쳤던 문제
PR : https://github.com/todo-team-01/todo-max/pull/74
